[project]
name = "adventofcode-24"
version = "0.6.1"
description = "Advent of Code 2024"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.1.3",
    "pygame>=2.6.1",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "ruff>=0.8.2",
]
